In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_ratings = pd.read_csv('./data/Ratings.csv')
df_ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [4]:
df_ratings.isna().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [21]:
df_ratings[df_ratings.duplicated(subset=['User-ID', 'ISBN'], keep=False)]

Empty DataFrame
Columns: [User-ID, ISBN, Book-Rating]
Index: []

In [5]:
df_users = pd.read_csv('./data/Users.csv')
df_users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [6]:
df_users.isna().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [25]:
df_users.loc[df_users['Age'].idxmax()]

User-ID                                      20857
Location    stuttgart, baden-wuerttemberg, germany
Age                                          244.0
Name: 20856, dtype: object

In [26]:
df_users.iloc[20850:20860]

       User-ID                                  Location    Age
20850    20851       lübeck, schleswig-holstein, germany    0.0
20851    20852         nordenham, niedersachsen, germany    NaN
20852    20853                               nürnberg, ,    0.0
20853    20854         oldenburg, niedersachsen, germany    NaN
20854    20855  rheinfelden, baden-wuerttemberg, germany    NaN
20855    20856   schaffhausen, schaffhausen, switzerland    0.0
20856    20857    stuttgart, baden-wuerttemberg, germany  244.0
20857    20858    siegburg, nordrhein-westfalen, germany   24.0
20858    20859      tübingen, baden-württemberg, germany    0.0
20859    20860                    las vegas, nevada, usa   62.0

In [39]:
df_users['Age'] = pd.to_numeric(df_users['Age'], errors='coerce')
weird_age_rows = df_users[df_users['Age'].isna()]
weird_age_rows.iloc[50:100]

     User-ID                                           Location  Age
109      110                              peoira, illinois, usa  NaN
112      113                     san francisco, california, usa  NaN
114      115                                  canton, ohio, usa  NaN
115      116                            burien, washington, usa  NaN
120      121                          rochester, minnesota, usa  NaN
121      122                     charlotte, north carolina, usa  NaN
127      128                    allison park, pennsylvania, usa  NaN
129      130                                 roma, lazio, italy  NaN
130      131                   chapel hill, north carolina, usa  NaN
133      134  canberra, australian capital territory, australia  NaN
134      135                           berkshire, new york, usa  NaN
135      136                        sacramento, california, usa  NaN
136      137                vancouver, british columbia, canada  NaN
140      141                              darien, new york, usa  NaN
141      142                                 derby, kansas, usa  NaN
144      145                inverness, scotland, united kingdom  NaN
145      146                                la, california, usa  NaN
146      147                     west haverstraw, new york, usa  NaN
148      149                           ljubljana, n/a, slovenia  NaN
150      151              darwin, northern territory, australia  NaN
153      154                    saskatoon, saskatchewan, canada  NaN
154      155                                lion, abruzzo, peru  NaN
158      159                           plymouth, minnesota, usa  NaN
161      162                              newark, delaware, usa  NaN
162      163                      carlsbad, california, vietnam  NaN
166      167                               helena, montana, usa  NaN
168      169                           arlington, virginia, usa  NaN
169      170                              roswell, georgia, usa  NaN
172      173                                    ames, iowa, usa  NaN
174      175                               porto, n/a, portugal  NaN
178      179                        wazirabad, punjab, pakistan  NaN
179      180                         copenhagen n, n/a, denmark  NaN
180      181                           karachi, sindh, pakistan  NaN
183      184                           seattle, washington, usa  NaN
185      186                  jacksonville, north carolina, usa  NaN
191      192                         sunnyvale, california, usa  NaN
193      194                         lake forest, illinois, usa  NaN
196      197                         brantford, ontario, canada  NaN
200      201                            sharjah, sharjah, u.a.e  NaN
202      203                    charleston, south carolina, usa  NaN
206      207                          west bend, wisconsin, usa  NaN
207      208                            bremen, bremen, germany  NaN
212      213                          gainesville, florida, usa  NaN
216      217                        spencer, massachusetts, usa  NaN
218      219                    bismark, sachsen-anhalt, greece  NaN
221      222                       kingston, massachusetts, usa  NaN
222      223                        wazirabad, punjab, pakistan  NaN
223      224                           strafford, missouri, usa  NaN
224      225                                  elgin, texas, usa  NaN
225      226                            new york, new york, usa  NaN

In [56]:
df_users['Original-Age'] = df_users['Age']

# Convert 'Age' to numeric, invalid values will become NaN
df_users['Age'] = pd.to_numeric(df_users['Age'], errors='coerce')

# Filter rows where 'Age' is NaN (invalid values that were coerced)
weird_age_rows = df_users[df_users['Original-Age'].notna() & df_users['Age'].isna()]

# Display the 'User-ID' and the original 'Age' before coercion
weird_age_rows[['Age', 'Original-Age']]

Empty DataFrame
Columns: [Age, Original-Age]
Index: []

In [13]:
df_books = pd.read_csv('./data/Books.csv', low_memory=False)
df_books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [8]:
df_books.isna().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [12]:
df_books[df_books.duplicated()]

Empty DataFrame
Columns: [ISBN, Book-Title, Book-Author, Year-Of-Publication, Publisher, Image-URL-S, Image-URL-M, Image-URL-L]
Index: []

In [66]:
print(df_users.shape)
print(df_books.shape)

(278858, 4)
(271360, 8)

In [75]:
existing_user_ids = df_users['User-ID'].unique()
existing_book_isbns = df_books['ISBN'].unique()
print(len(existing_user_ids))
print(len(existing_book_isbns))

print("RATING SHAPE:", df_ratings.shape)
df_ratings_filtered = df_ratings[df_ratings['User-ID'].isin(existing_user_ids) & df_ratings['ISBN'].isin(existing_book_isbns)]
df_ratings_filtered1 = df_ratings[df_ratings['User-ID'].isin(existing_user_ids)]
df_ratings_filtered2 = df_ratings[df_ratings['ISBN'].isin(existing_book_isbns)]
print(df_ratings_filtered)
print(df_ratings_filtered1)
print(df_ratings_filtered2)

278858
271360
RATING SHAPE: (1149780, 3)
         User-ID        ISBN  Book-Rating
0         276725  034545104X            0
1         276726  0155061224            5
2         276727  0446520802            0
3         276729  052165615X            3
4         276729  0521795028            6
...          ...         ...          ...
1149774   276704  0876044011            0
1149775   276704  1563526298            9
1149776   276706  0679447156            0
1149777   276709  0515107662           10
1149778   276721  0590442449           10

[1031136 rows x 3 columns]
         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]
         User-ID        ISBN  Book-Rating
0         276725  034545104X            0
1         276726  0155061224            5
2         276727  0446520802            0
3         276729  052165615X            3
4         276729  0521795028            6
...          ...         ...          ...
1149774   276704  0876044011            0
1149775   276704  1563526298            9
1149776   276706  0679447156            0
1149777   276709  0515107662           10
1149778   276721  0590442449           10

[1031136 rows x 3 columns]

In [14]:
df = pd.read_csv('./ResultBooks.csv')
df

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,60973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
249017,449906736,Flashpoints: Promise and Peril in a New World,Robin Wright,1993,Ballantine Books,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...
249018,440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
249019,525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
249020,192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
249021,767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...